/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemasRouteImport } from './routes/temas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ArquivoRouteImport } from './routes/arquivo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TimeSlugRouteImport } from './routes/time.$slug'
import { Route as AutorSlugRouteImport } from './routes/autor.$slug'
import { Route as AssuntoSlugRouteImport } from './routes/assunto.$slug'
import { Route as ArquivoAnoRouteImport } from './routes/arquivo.$ano'
import { Route as AdminCriarContaRouteImport } from './routes/admin_.criar-conta'
import { Route as AdminTemasRouteImport } from './routes/admin.temas'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminMateriasRouteImport } from './routes/admin.materias'
import { Route as AdminImportarRouteImport } from './routes/admin.importar'
import { Route as AdminContatosRouteImport } from './routes/admin.contatos'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAutoresRouteImport } from './routes/admin.autores'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminMateriasIndexRouteImport } from './routes/admin.materias.index'
import { Route as ArquivoAnoMesRouteImport } from './routes/arquivo.$ano.$mes'
import { Route as AdminPostsNovoRouteImport } from './routes/admin.posts.novo'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as AdminMateriasNovaRouteImport } from './routes/admin.materias.nova'
import { Route as AdminMateriasIdRouteImport } from './routes/admin.materias.$id'
import { Route as ApiPublicHooksBackupAutomaticoRouteImport } from './routes/api/public/hooks/backup-automatico'

const TemasRoute = TemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivoRoute = ArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TimeSlugRoute = TimeSlugRouteImport.update({
  id: '/time/$slug',
  path: '/time/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorSlugRoute = AutorSlugRouteImport.update({
  id: '/autor/$slug',
  path: '/autor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuntoSlugRoute = AssuntoSlugRouteImport.update({
  id: '/assunto/$slug',
  path: '/assunto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivoAnoRoute = ArquivoAnoRouteImport.update({
  id: '/$ano',
  path: '/$ano',
  getParentRoute: () => ArquivoRoute,
} as any)
const AdminCriarContaRoute = AdminCriarContaRouteImport.update({
  id: '/admin_/criar-conta',
  path: '/admin/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemasRoute = AdminTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriasRoute = AdminMateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportarRoute = AdminImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContatosRoute = AdminContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutoresRoute = AdminAutoresRouteImport.update({
  id: '/autores',
  path: '/autores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminMateriasIndexRoute = AdminMateriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMateriasRoute,
} as any)
const ArquivoAnoMesRoute = ArquivoAnoMesRouteImport.update({
  id: '/$mes',
  path: '/$mes',
  getParentRoute: () => ArquivoAnoRoute,
} as any)
const AdminPostsNovoRoute = AdminPostsNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminMateriasNovaRoute = AdminMateriasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminMateriasRoute,
} as any)
const AdminMateriasIdRoute = AdminMateriasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMateriasRoute,
} as any)
const ApiPublicHooksBackupAutomaticoRoute =
  ApiPublicHooksBackupAutomaticoRouteImport.update({
    id: '/api/public/hooks/backup-automatico',
    path: '/api/public/hooks/backup-automatico',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/arquivo': typeof ArquivoRouteWithChildren
  '/busca': typeof BuscaRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/feed': typeof FeedRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temas': typeof TemasRoute
  '/admin/autores': typeof AdminAutoresRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/materias': typeof AdminMateriasRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/temas': typeof AdminTemasRoute
  '/admin/criar-conta': typeof AdminCriarContaRoute
  '/arquivo/$ano': typeof ArquivoAnoRouteWithChildren
  '/assunto/$slug': typeof AssuntoSlugRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/time/$slug': typeof TimeSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/materias/$id': typeof AdminMateriasIdRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/novo': typeof AdminPostsNovoRoute
  '/arquivo/$ano/$mes': typeof ArquivoAnoMesRoute
  '/admin/materias/': typeof AdminMateriasIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/api/public/hooks/backup-automatico': typeof ApiPublicHooksBackupAutomaticoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/arquivo': typeof ArquivoRouteWithChildren
  '/busca': typeof BuscaRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/feed': typeof FeedRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temas': typeof TemasRoute
  '/admin/autores': typeof AdminAutoresRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/temas': typeof AdminTemasRoute
  '/admin/criar-conta': typeof AdminCriarContaRoute
  '/arquivo/$ano': typeof ArquivoAnoRouteWithChildren
  '/assunto/$slug': typeof AssuntoSlugRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/time/$slug': typeof TimeSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/materias/$id': typeof AdminMateriasIdRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/novo': typeof AdminPostsNovoRoute
  '/arquivo/$ano/$mes': typeof ArquivoAnoMesRoute
  '/admin/materias': typeof AdminMateriasIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/api/public/hooks/backup-automatico': typeof ApiPublicHooksBackupAutomaticoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/arquivo': typeof ArquivoRouteWithChildren
  '/busca': typeof BuscaRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/feed': typeof FeedRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temas': typeof TemasRoute
  '/admin/autores': typeof AdminAutoresRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/materias': typeof AdminMateriasRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/temas': typeof AdminTemasRoute
  '/admin_/criar-conta': typeof AdminCriarContaRoute
  '/arquivo/$ano': typeof ArquivoAnoRouteWithChildren
  '/assunto/$slug': typeof AssuntoSlugRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/time/$slug': typeof TimeSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/materias/$id': typeof AdminMateriasIdRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/novo': typeof AdminPostsNovoRoute
  '/arquivo/$ano/$mes': typeof ArquivoAnoMesRoute
  '/admin/materias/': typeof AdminMateriasIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/api/public/hooks/backup-automatico': typeof ApiPublicHooksBackupAutomaticoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/arquivo'
    | '/busca'
    | '/completar-perfil'
    | '/conta'
    | '/entrar'
    | '/fale-conosco'
    | '/feed'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/temas'
    | '/admin/autores'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/contatos'
    | '/admin/importar'
    | '/admin/materias'
    | '/admin/posts'
    | '/admin/temas'
    | '/admin/criar-conta'
    | '/arquivo/$ano'
    | '/assunto/$slug'
    | '/autor/$slug'
    | '/time/$slug'
    | '/admin/'
    | '/admin/materias/$id'
    | '/admin/materias/nova'
    | '/admin/posts/$id'
    | '/admin/posts/novo'
    | '/arquivo/$ano/$mes'
    | '/admin/materias/'
    | '/admin/posts/'
    | '/api/public/hooks/backup-automatico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/arquivo'
    | '/busca'
    | '/completar-perfil'
    | '/conta'
    | '/entrar'
    | '/fale-conosco'
    | '/feed'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/temas'
    | '/admin/autores'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/contatos'
    | '/admin/importar'
    | '/admin/temas'
    | '/admin/criar-conta'
    | '/arquivo/$ano'
    | '/assunto/$slug'
    | '/autor/$slug'
    | '/time/$slug'
    | '/admin'
    | '/admin/materias/$id'
    | '/admin/materias/nova'
    | '/admin/posts/$id'
    | '/admin/posts/novo'
    | '/arquivo/$ano/$mes'
    | '/admin/materias'
    | '/admin/posts'
    | '/api/public/hooks/backup-automatico'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/arquivo'
    | '/busca'
    | '/completar-perfil'
    | '/conta'
    | '/entrar'
    | '/fale-conosco'
    | '/feed'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/temas'
    | '/admin/autores'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/contatos'
    | '/admin/importar'
    | '/admin/materias'
    | '/admin/posts'
    | '/admin/temas'
    | '/admin_/criar-conta'
    | '/arquivo/$ano'
    | '/assunto/$slug'
    | '/autor/$slug'
    | '/time/$slug'
    | '/admin/'
    | '/admin/materias/$id'
    | '/admin/materias/nova'
    | '/admin/posts/$id'
    | '/admin/posts/novo'
    | '/arquivo/$ano/$mes'
    | '/admin/materias/'
    | '/admin/posts/'
    | '/api/public/hooks/backup-automatico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArquivoRoute: typeof ArquivoRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  ContaRoute: typeof ContaRoute
  EntrarRoute: typeof EntrarRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  FeedRoute: typeof FeedRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemasRoute: typeof TemasRoute
  AdminCriarContaRoute: typeof AdminCriarContaRoute
  AssuntoSlugRoute: typeof AssuntoSlugRoute
  AutorSlugRoute: typeof AutorSlugRoute
  TimeSlugRoute: typeof TimeSlugRoute
  ApiPublicHooksBackupAutomaticoRoute: typeof ApiPublicHooksBackupAutomaticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temas': {
      id: '/temas'
      path: '/temas'
      fullPath: '/temas'
      preLoaderRoute: typeof TemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivo': {
      id: '/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof ArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/time/$slug': {
      id: '/time/$slug'
      path: '/time/$slug'
      fullPath: '/time/$slug'
      preLoaderRoute: typeof TimeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor/$slug': {
      id: '/autor/$slug'
      path: '/autor/$slug'
      fullPath: '/autor/$slug'
      preLoaderRoute: typeof AutorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assunto/$slug': {
      id: '/assunto/$slug'
      path: '/assunto/$slug'
      fullPath: '/assunto/$slug'
      preLoaderRoute: typeof AssuntoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivo/$ano': {
      id: '/arquivo/$ano'
      path: '/$ano'
      fullPath: '/arquivo/$ano'
      preLoaderRoute: typeof ArquivoAnoRouteImport
      parentRoute: typeof ArquivoRoute
    }
    '/admin_/criar-conta': {
      id: '/admin_/criar-conta'
      path: '/admin/criar-conta'
      fullPath: '/admin/criar-conta'
      preLoaderRoute: typeof AdminCriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/temas': {
      id: '/admin/temas'
      path: '/temas'
      fullPath: '/admin/temas'
      preLoaderRoute: typeof AdminTemasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materias': {
      id: '/admin/materias'
      path: '/materias'
      fullPath: '/admin/materias'
      preLoaderRoute: typeof AdminMateriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importar': {
      id: '/admin/importar'
      path: '/importar'
      fullPath: '/admin/importar'
      preLoaderRoute: typeof AdminImportarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contatos': {
      id: '/admin/contatos'
      path: '/contatos'
      fullPath: '/admin/contatos'
      preLoaderRoute: typeof AdminContatosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/autores': {
      id: '/admin/autores'
      path: '/autores'
      fullPath: '/admin/autores'
      preLoaderRoute: typeof AdminAutoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/materias/': {
      id: '/admin/materias/'
      path: '/'
      fullPath: '/admin/materias/'
      preLoaderRoute: typeof AdminMateriasIndexRouteImport
      parentRoute: typeof AdminMateriasRoute
    }
    '/arquivo/$ano/$mes': {
      id: '/arquivo/$ano/$mes'
      path: '/$mes'
      fullPath: '/arquivo/$ano/$mes'
      preLoaderRoute: typeof ArquivoAnoMesRouteImport
      parentRoute: typeof ArquivoAnoRoute
    }
    '/admin/posts/novo': {
      id: '/admin/posts/novo'
      path: '/novo'
      fullPath: '/admin/posts/novo'
      preLoaderRoute: typeof AdminPostsNovoRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/materias/nova': {
      id: '/admin/materias/nova'
      path: '/nova'
      fullPath: '/admin/materias/nova'
      preLoaderRoute: typeof AdminMateriasNovaRouteImport
      parentRoute: typeof AdminMateriasRoute
    }
    '/admin/materias/$id': {
      id: '/admin/materias/$id'
      path: '/$id'
      fullPath: '/admin/materias/$id'
      preLoaderRoute: typeof AdminMateriasIdRouteImport
      parentRoute: typeof AdminMateriasRoute
    }
    '/api/public/hooks/backup-automatico': {
      id: '/api/public/hooks/backup-automatico'
      path: '/api/public/hooks/backup-automatico'
      fullPath: '/api/public/hooks/backup-automatico'
      preLoaderRoute: typeof ApiPublicHooksBackupAutomaticoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminMateriasRouteChildren {
  AdminMateriasIdRoute: typeof AdminMateriasIdRoute
  AdminMateriasNovaRoute: typeof AdminMateriasNovaRoute
  AdminMateriasIndexRoute: typeof AdminMateriasIndexRoute
}

const AdminMateriasRouteChildren: AdminMateriasRouteChildren = {
  AdminMateriasIdRoute: AdminMateriasIdRoute,
  AdminMateriasNovaRoute: AdminMateriasNovaRoute,
  AdminMateriasIndexRoute: AdminMateriasIndexRoute,
}

const AdminMateriasRouteWithChildren = AdminMateriasRoute._addFileChildren(
  AdminMateriasRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNovoRoute: typeof AdminPostsNovoRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNovoRoute: AdminPostsNovoRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminAutoresRoute: typeof AdminAutoresRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminContatosRoute: typeof AdminContatosRoute
  AdminImportarRoute: typeof AdminImportarRoute
  AdminMateriasRoute: typeof AdminMateriasRouteWithChildren
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminTemasRoute: typeof AdminTemasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutoresRoute: AdminAutoresRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminContatosRoute: AdminContatosRoute,
  AdminImportarRoute: AdminImportarRoute,
  AdminMateriasRoute: AdminMateriasRouteWithChildren,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminTemasRoute: AdminTemasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArquivoAnoRouteChildren {
  ArquivoAnoMesRoute: typeof ArquivoAnoMesRoute
}

const ArquivoAnoRouteChildren: ArquivoAnoRouteChildren = {
  ArquivoAnoMesRoute: ArquivoAnoMesRoute,
}

const ArquivoAnoRouteWithChildren = ArquivoAnoRoute._addFileChildren(
  ArquivoAnoRouteChildren,
)

interface ArquivoRouteChildren {
  ArquivoAnoRoute: typeof ArquivoAnoRouteWithChildren
}

const ArquivoRouteChildren: ArquivoRouteChildren = {
  ArquivoAnoRoute: ArquivoAnoRouteWithChildren,
}

const ArquivoRouteWithChildren =
  ArquivoRoute._addFileChildren(ArquivoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  ArquivoRoute: ArquivoRouteWithChildren,
  BuscaRoute: BuscaRoute,
  CompletarPerfilRoute: CompletarPerfilRoute,
  ContaRoute: ContaRoute,
  EntrarRoute: EntrarRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  FeedRoute: FeedRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemasRoute: TemasRoute,
  AdminCriarContaRoute: AdminCriarContaRoute,
  AssuntoSlugRoute: AssuntoSlugRoute,
  AutorSlugRoute: AutorSlugRoute,
  TimeSlugRoute: TimeSlugRoute,
  ApiPublicHooksBackupAutomaticoRoute: ApiPublicHooksBackupAutomaticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
