
ALTER TABLE public.importacao_estado
  ADD COLUMN IF NOT EXISTS em_execucao BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS batimento_em TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS indice_pagina INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ultimo_wp_id BIGINT,
  ADD COLUMN IF NOT EXISTS materia_atual TEXT,
  ADD COLUMN IF NOT EXISTS imagem_atual TEXT,
  ADD COLUMN IF NOT EXISTS ult_importados INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ult_atualizados INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ult_pulados INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ult_erros INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bytes_baixados BIGINT NOT NULL DEFAULT 0;
